"""
GoalFlow — Export Service
CSV and Excel report generation with GoalFlow branding.
"""

import csv
import io
from decimal import Decimal
from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select
from sqlalchemy.orm import selectinload

from app.models.goal import GoalSheet, Goal, Cycle
from app.models.checkin import CheckIn
from app.models.user import User


ACHIEVEMENT_COLUMNS = [
    "Employee Name", "Department", "Goal Title", "Thrust Area", "UoM",
    "Target", "Q1 Actual", "Q1 Score", "Q2 Actual", "Q2 Score",
    "Q3 Actual", "Q3 Score", "Q4 Actual", "Q4 Score", "Status",
]


async def generate_achievement_report(
    db: AsyncSession, cycle_id: str, format: str = "csv",
) -> tuple[bytes, str]:
    """Generate achievement report as CSV or Excel."""
    # Fetch data
    sheets_result = await db.execute(
        select(GoalSheet)
        .options(selectinload(GoalSheet.goals).selectinload(Goal.checkins),
                 selectinload(GoalSheet.employee))
        .where(GoalSheet.cycle_id == cycle_id)
    )
    sheets = sheets_result.scalars().all()

    rows = []
    for sheet in sheets:
        emp = sheet.employee
        for goal in sheet.goals:
            row = {
                "Employee Name": emp.name if emp else "Unknown",
                "Department": emp.department if emp else "",
                "Goal Title": goal.title,
                "Thrust Area": goal.thrust_area,
                "UoM": goal.uom_type,
                "Target": str(goal.target_value or goal.target_date or ""),
                "Status": sheet.status,
            }
            for q in ["Q1", "Q2", "Q3", "Q4"]:
                ci = next((c for c in goal.checkins if c.quarter == q), None)
                row[f"{q} Actual"] = str(ci.actual_value or ci.actual_date or "") if ci else ""
                row[f"{q} Score"] = str(ci.computed_score or "") if ci else ""
            rows.append(row)

    if format == "excel":
        return _generate_excel(rows, ACHIEVEMENT_COLUMNS, "Achievement Report"), \
            "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
    else:
        return _generate_csv(rows, ACHIEVEMENT_COLUMNS), "text/csv"


async def generate_completion_report(
    db: AsyncSession, cycle_id: str, quarter: str | None = None,
) -> tuple[bytes, str]:
    """Generate completion status report as CSV."""
    sheets_result = await db.execute(
        select(GoalSheet)
        .options(selectinload(GoalSheet.employee))
        .where(GoalSheet.cycle_id == cycle_id)
    )
    sheets = sheets_result.scalars().all()

    columns = ["Employee Name", "Department", "Sheet Status", "Goals Count", "Submitted At", "Approved At"]
    rows = []
    for sheet in sheets:
        emp = sheet.employee
        rows.append({
            "Employee Name": emp.name if emp else "Unknown",
            "Department": emp.department if emp else "",
            "Sheet Status": sheet.status,
            "Goals Count": len(sheet.goals) if hasattr(sheet, 'goals') else 0,
            "Submitted At": str(sheet.submitted_at or ""),
            "Approved At": str(sheet.approved_at or ""),
        })

    return _generate_csv(rows, columns), "text/csv"


def _generate_csv(rows: list[dict], columns: list[str]) -> bytes:
    """Generate CSV with BOM for Excel compatibility."""
    output = io.StringIO()
    output.write('\ufeff')  # BOM
    writer = csv.DictWriter(output, fieldnames=columns, extrasaction='ignore')
    writer.writeheader()
    writer.writerows(rows)
    return output.getvalue().encode("utf-8-sig")


def _generate_excel(rows: list[dict], columns: list[str], title: str) -> bytes:
    """Generate branded Excel file."""
    wb = Workbook()
    ws = wb.active
    ws.title = title

    # Branding header
    header_fill = PatternFill(start_color="4F46E5", end_color="4F46E5", fill_type="solid")
    header_font = Font(name="Calibri", size=11, bold=True, color="FFFFFF")
    title_font = Font(name="Calibri", size=16, bold=True, color="4F46E5")
    thin_border = Border(
        left=Side(style='thin'), right=Side(style='thin'),
        top=Side(style='thin'), bottom=Side(style='thin'),
    )

    # Title row
    ws.merge_cells(start_row=1, start_column=1, end_row=1, end_column=len(columns))
    ws.cell(row=1, column=1, value=f"GoalFlow — {title}").font = title_font
    ws.row_dimensions[1].height = 30

    # Subtitle
    ws.merge_cells(start_row=2, start_column=1, end_row=2, end_column=len(columns))
    ws.cell(row=2, column=1, value="Generated by GoalFlow Portal").font = Font(
        name="Calibri", size=9, italic=True, color="888888"
    )

    # Column headers (row 4)
    for col_idx, col_name in enumerate(columns, 1):
        cell = ws.cell(row=4, column=col_idx, value=col_name)
        cell.font = header_font
        cell.fill = header_fill
        cell.alignment = Alignment(horizontal='center')
        cell.border = thin_border

    # Data rows
    for row_idx, row_data in enumerate(rows, 5):
        for col_idx, col_name in enumerate(columns, 1):
            cell = ws.cell(row=row_idx, column=col_idx, value=row_data.get(col_name, ""))
            cell.border = thin_border

    # Auto-width columns
    for col_idx, col_name in enumerate(columns, 1):
        max_len = max(len(col_name), *(len(str(r.get(col_name, ""))) for r in rows)) if rows else len(col_name)
        ws.column_dimensions[chr(64 + col_idx) if col_idx <= 26 else "A"].width = min(max_len + 4, 40)

    output = io.BytesIO()
    wb.save(output)
    return output.getvalue()
